### ISSUE TITLE
Trees fall off if tree is too complex

### ISSUE THREAD

**Issue by richelbilderbeek** [Joshua260403/geneak#23]
Impressed by how it looks! You even handle polytomies well!

Too badly, for more complex trees, the graphics fall off:

![2019-05-31-193350_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/58723693-0cf57480-83db-11e9-9f51-b5efcde1d438.png)

An option would be to add a 'Save' option, so the user can save the graphic.

**Comment by DynCoder** [comment]
Try the arrow keys :+1:

**Comment by richelbilderbeek** [comment]
Intheredeed! Well gedone!
