### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by richelbilderbeek** [Joshua260403/geneak#8]
Build does not work :neutral_face:

**Comment by richelbilderbeek** [comment]
I changed the Travis script. The [Travis log](https://travis-ci.org/Joshua260403/geneak/builds/527507260#L1093) only notifies about an OCLint improvement. I am pretty sure you can fix that yourself :+1: 

I assume I did what you wanted me to do ...

 * if yes, close the Issue
 * if no, let me know
 
Good luck making something awesome!

**Comment by DynCoder** [comment]
Cool, it works. Thanks alot!
EDIT: 🍀 🌱
